/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting2016;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author adam
 */
public class FormPit extends javax.swing.JFrame {

    /**
     * Creates new form FormPit
     */
    public FormPit() {
        
        try   
    {
        // sets look and feely
        UIManager.setLookAndFeel
            ("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch(Exception e)  
    {}  
        initComponents();
        
        
        
        
         // sets window to center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        double width = dim.getWidth();
        double height = dim.getHeight();
    
        // alerts user if screen resolution is below 1024x768 
        if (width<1024 || height<768)
        
        {
            JOptionPane.showMessageDialog(null,
            "Your screen resolution is not supported. Some "
                    + "elements may not appear or may appear incorrectly.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }
    
        // sets window to center of screen
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        telePanel = new javax.swing.JPanel();
        teleLabel1 = new javax.swing.JLabel();
        teleLabel2 = new javax.swing.JLabel();
        teleLabel3 = new javax.swing.JLabel();
        teleLabel4 = new javax.swing.JLabel();
        teleLabel5 = new javax.swing.JLabel();
        teleLabel6 = new javax.swing.JLabel();
        teleLabel7 = new javax.swing.JLabel();
        teleLabel8 = new javax.swing.JLabel();
        teleLabel9 = new javax.swing.JLabel();
        teleLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teleText1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        teleText2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        teleText3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        teleText4 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        teleText5 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        teleText6 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        teleText7 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        teleText8 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        teleText9 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        teleText10 = new javax.swing.JTextArea();
        autoPanel = new javax.swing.JPanel();
        autoLabel1 = new javax.swing.JLabel();
        autoLabel2 = new javax.swing.JLabel();
        autoLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autoText1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        autoText2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        autoText3 = new javax.swing.JTextArea();
        pitSave = new javax.swing.JButton();
        optionsNick = new java.awt.TextField();
        optionsNickLabel = new javax.swing.JLabel();
        optionsTeam = new java.awt.TextField();
        optionsTeamLabel = new javax.swing.JLabel();
        optionsScouter = new java.awt.TextField();
        optionsScouterLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pit Sheet");

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        telePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Teleoperation"));

        teleLabel1.setText("Ideal position in team: Defender, Breacher, Shooter, etc?");

        teleLabel2.setText("What can your human player do? (Bowl, spy)");

        teleLabel3.setText("What goals do you shoot for? (High / Low)");

        teleLabel4.setText("Plans for boulders? (Shoot, pass, other?)");

        teleLabel5.setText("Which defenses can you cross alone?");

        teleLabel6.setText("Do you help allies cross any defenses? (Yes / No)");

        teleLabel7.setText("What defenses can this robot most easily breach? (Preference) ");

        teleLabel8.setText("What defenses are the hardest for this robot to breach?");

        teleLabel9.setText("Can you challenge the enemy castle? (Challenge / Climb)");

        teleLabel10.setText("What ally would best compliment your robot?");

        teleText1.setColumns(20);
        teleText1.setRows(1);
        jScrollPane4.setViewportView(teleText1);

        teleText2.setColumns(20);
        teleText2.setRows(1);
        jScrollPane5.setViewportView(teleText2);

        teleText3.setColumns(20);
        teleText3.setRows(1);
        jScrollPane6.setViewportView(teleText3);

        teleText4.setColumns(20);
        teleText4.setRows(1);
        jScrollPane7.setViewportView(teleText4);

        teleText5.setColumns(20);
        teleText5.setRows(1);
        jScrollPane8.setViewportView(teleText5);

        teleText6.setColumns(20);
        teleText6.setRows(1);
        jScrollPane9.setViewportView(teleText6);

        teleText7.setColumns(20);
        teleText7.setRows(1);
        jScrollPane10.setViewportView(teleText7);

        teleText8.setColumns(20);
        teleText8.setRows(1);
        jScrollPane11.setViewportView(teleText8);

        teleText9.setColumns(20);
        teleText9.setRows(1);
        jScrollPane12.setViewportView(teleText9);

        teleText10.setColumns(20);
        teleText10.setRows(1);
        jScrollPane13.setViewportView(teleText10);

        javax.swing.GroupLayout telePanelLayout = new javax.swing.GroupLayout(telePanel);
        telePanel.setLayout(telePanelLayout);
        telePanelLayout.setHorizontalGroup(
            telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel7)
                    .addComponent(teleLabel8)
                    .addComponent(teleLabel2)
                    .addComponent(teleLabel9)
                    .addComponent(teleLabel10)
                    .addComponent(teleLabel1)
                    .addComponent(teleLabel3)
                    .addComponent(teleLabel4)
                    .addComponent(teleLabel5)
                    .addComponent(teleLabel6))
                .addGap(17, 17, 17)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        telePanelLayout.setVerticalGroup(
            telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel4)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel5)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel6)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel7)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel8)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel9)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teleLabel10)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autonomous"));
        autoPanel.setPreferredSize(new java.awt.Dimension(380, 125));

        autoLabel1.setText("Can the robot reach defenses in autonomous? Which ones?");

        autoLabel2.setText("Can the robot cross defenses in autonomous? Which ones?");

        autoLabel3.setText("Can the robot cross defenses in autonomous? Which ones?");

        autoText1.setColumns(20);
        autoText1.setRows(1);
        jScrollPane1.setViewportView(autoText1);

        autoText2.setColumns(20);
        autoText2.setRows(1);
        jScrollPane2.setViewportView(autoText2);

        autoText3.setColumns(20);
        autoText3.setRows(1);
        jScrollPane3.setViewportView(autoText3);

        javax.swing.GroupLayout autoPanelLayout = new javax.swing.GroupLayout(autoPanel);
        autoPanel.setLayout(autoPanelLayout);
        autoPanelLayout.setHorizontalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoLabel1)
                    .addComponent(autoLabel2)
                    .addComponent(autoLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        autoPanelLayout.setVerticalGroup(
            autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(autoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pitSave.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        pitSave.setText("Save");
        pitSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pitSaveActionPerformed(evt);
            }
        });

        optionsNick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optionsNickKeyReleased(evt);
            }
        });

        optionsNickLabel.setText("Team name");

        optionsTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsTeamActionPerformed(evt);
            }
        });
        optionsTeam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optionsTeamKeyReleased(evt);
            }
        });

        optionsTeamLabel.setText("Team #");

        optionsScouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                optionsScouterKeyReleased(evt);
            }
        });

        optionsScouterLabel.setText("Scouter name");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(autoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(pitSave)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(optionsScouterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsScouter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsTeamLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsNickLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsNick, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsScouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionsScouterLabel)
                    .addComponent(optionsTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionsTeamLabel)
                    .addComponent(optionsNickLabel)
                    .addComponent(optionsNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(autoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pitSave)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionsTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsTeamActionPerformed
        optionsChanged();
    }//GEN-LAST:event_optionsTeamActionPerformed

    private void optionsTeamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optionsTeamKeyReleased
        optionsChanged();
    }//GEN-LAST:event_optionsTeamKeyReleased

    private void optionsNickKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optionsNickKeyReleased
        optionsChanged();
    }//GEN-LAST:event_optionsNickKeyReleased

    private void pitSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pitSaveActionPerformed
        optionsSave();
    }//GEN-LAST:event_pitSaveActionPerformed

    private void optionsScouterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optionsScouterKeyReleased
        optionsChanged();
    }//GEN-LAST:event_optionsScouterKeyReleased

    
    private void optionsChanged() 
    {
    
        int submitInt = 0;
            
        if ("".equals(optionsScouter.getText()))    
                submitInt++;
        else if (optionsScouter.getText().contains("-"))
        {
            textFieldCondClear(optionsScouter);
        }
        if ("".equals(optionsNick.getText()))
                submitInt++;
        else if (optionsNick.getText().contains("-"))
        {
            textFieldCondClear(optionsNick);
        }
        if ("".equals(optionsTeam.getText()))
                submitInt++;
        else if (optionsTeam.getText().contains("-"))
        {
            textFieldCondClear(optionsTeam);
        }
    
        pitSave.setEnabled(submitInt == 0);
    
    }
    
    
    private void optionsSave()
    {
        
        
    String text =
            "Pit Sheet\n\n" +
            optionsScouterLabel.getText() + ": " + optionsScouter.getText() + "\n\n" +
            optionsTeamLabel.getText() + ": " + optionsTeam.getText() + "\n\n" +
            optionsNickLabel.getText() + ": " + optionsNick.getText() + "\n\n\n\n" +
            
            "Autonomous:\n\t" +
            autoLabel1.getText() + "\n\t\t" + autoText1.getText() + "\n\n\t" +
            autoLabel2.getText() + "\n\t\t" + autoText2.getText() + "\n\n\t" +
            autoLabel3.getText() + "\n\t\t" + autoText3.getText() + "\n\n\n" +
            
            "Teleoperation\n\t" +
            teleLabel1.getText() + "\n\t\t" + teleText1.getText() + "\n\n\t" +
            teleLabel2.getText() + "\n\t\t" + teleText2.getText() + "\n\n\t" +
            teleLabel3.getText() + "\n\t\t" + teleText3.getText() + "\n\n\t" +
            teleLabel4.getText() + "\n\t\t" + teleText4.getText() + "\n\n\t" +
            teleLabel5.getText() + "\n\t\t" + teleText5.getText() + "\n\n\t" +
            teleLabel6.getText() + "\n\t\t" + teleText6.getText() + "\n\n\t" +
            teleLabel7.getText() + "\n\t\t" + teleText7.getText() + "\n\n\t" +
            teleLabel8.getText() + "\n\t\t" + teleText8.getText() + "\n\n\t" +
            teleLabel9.getText() + "\n\t\t" + teleText9.getText() + "\n\n\t" +
            teleLabel10.getText() + "\n\t\t" + teleText10.getText()
            ;    
    
    try 
            
        {
            // writes data sheet to file
            File scoutFile = new File("./PitSheets/PitSheet-" + optionsTeam.getText() 
                    + "-" + optionsNick.getText() + "-" + optionsScouter.getText() + ".txt");
            BufferedWriter output = new BufferedWriter(new FileWriter(scoutFile));
            output.write(text);
            output.close();
          
            JOptionPane.showMessageDialog(null,
            "Your sheet has been saved",
            "Success",
            JOptionPane.DEFAULT_OPTION);
        }
        catch ( IOException e )
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
            "Failed to write to Pit Scouting Sheet",
            "Error",
            JOptionPane.ERROR_MESSAGE);  
        }   
    }
    
    
    private void textFieldCondClear(java.awt.TextField field) {
        for (char c : field.getText().toCharArray())
            {
                if (!Character.isDigit(c))
                {
                    field.setText("");
                }
            }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autoLabel1;
    private javax.swing.JLabel autoLabel2;
    private javax.swing.JLabel autoLabel3;
    private javax.swing.JPanel autoPanel;
    private javax.swing.JTextArea autoText1;
    private javax.swing.JTextArea autoText2;
    private javax.swing.JTextArea autoText3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel mainPanel;
    private java.awt.TextField optionsNick;
    private javax.swing.JLabel optionsNickLabel;
    private java.awt.TextField optionsScouter;
    private javax.swing.JLabel optionsScouterLabel;
    private java.awt.TextField optionsTeam;
    private javax.swing.JLabel optionsTeamLabel;
    private javax.swing.JButton pitSave;
    private javax.swing.JLabel teleLabel1;
    private javax.swing.JLabel teleLabel10;
    private javax.swing.JLabel teleLabel2;
    private javax.swing.JLabel teleLabel3;
    private javax.swing.JLabel teleLabel4;
    private javax.swing.JLabel teleLabel5;
    private javax.swing.JLabel teleLabel6;
    private javax.swing.JLabel teleLabel7;
    private javax.swing.JLabel teleLabel8;
    private javax.swing.JLabel teleLabel9;
    private javax.swing.JPanel telePanel;
    private javax.swing.JTextArea teleText1;
    private javax.swing.JTextArea teleText10;
    private javax.swing.JTextArea teleText2;
    private javax.swing.JTextArea teleText3;
    private javax.swing.JTextArea teleText4;
    private javax.swing.JTextArea teleText5;
    private javax.swing.JTextArea teleText6;
    private javax.swing.JTextArea teleText7;
    private javax.swing.JTextArea teleText8;
    private javax.swing.JTextArea teleText9;
    // End of variables declaration//GEN-END:variables
}
