 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

// pending: remove individual scoring code 

package scouting2016;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.List;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adam
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws FileNotFoundException {
        
    try   
    {
        // sets look and feely
        UIManager.setLookAndFeel
            ("javax.swing.plaf.metal.MetalLookAndFeel");

    } 
    
    catch(Exception e)
        
    {
        // the user must be aware!
        // look and feel may be unsupported by platform
        JOptionPane.showMessageDialog(null,
        "The Scouting UI cannot be properly initialized. \n"
                + "The program will execute, but it may not "
                + "appear or function as intended.",
        "Error",
        JOptionPane.ERROR_MESSAGE);
    }
            
        // initializes functionality
        initComponents();       
        
        tableParse();
        
        windowSet();
        
        //makes window visible to user
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        mainMatchForm = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        introTable = new javax.swing.JTable();
        introView = new javax.swing.JButton();
        introRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(828, 652));
        setPreferredSize(new java.awt.Dimension(820, 624));

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Scouter Name", "Team #", "Match #", "Grand Total Points", "Overall Performance", "Driving System", "Driving System Functionality", "Mover System", "Mover System Functionality", "Foul Points", "Additional Comments", "Autonomous Points", "Teleoperation Points", "Coopertition Points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);
        //height 400

        mainMatchForm.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        mainMatchForm.setText("New Match Form");
        mainMatchForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMatchFormActionPerformed(evt);
            }
        });

        introTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team #", "Match #", "Scouter", "Highest Score", "Mean Score", "Win Rate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(introTable);

        introView.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        introView.setText("View Scouting Sheets");
        introView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introViewActionPerformed(evt);
            }
        });

        introRefresh.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        introRefresh.setText("Refresh");
        introRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mainMatchForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(introRefresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMatchForm)
                    .addComponent(introView)
                    .addComponent(introRefresh))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMatchFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMatchFormActionPerformed

        FormMatch match = new FormMatch();
        
    }//GEN-LAST:event_mainMatchFormActionPerformed

    private void introViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introViewActionPerformed
        Desktop desktop = Desktop.getDesktop();
        try {
            File dirOpen = new File("./Sheets");
            desktop.open(dirOpen);
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null,
            "Error opening default file explorer.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_introViewActionPerformed

    private void introRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introRefreshActionPerformed
        try
        {
            System.out.println("REFRESHING");
            tableParse();
        }
        catch (FileNotFoundException e)
        {
            
        }
    }//GEN-LAST:event_introRefreshActionPerformed

    
    private String[] tableParse() throws FileNotFoundException
    { 
        // TODO (unabridged edition)
        // currently just goes through each file and spits out a new row
        // for each new file read, will need it to go through each file,
        // determine an array of team numbers out of the files, then
        // for the stats mentioned in the columns, read through each
        // file in the team pool for the scores, determine the average
        // and max and such for them, then print out a new row
        // P.S. check if file name is malformed before reading from it
        
        int introRowCount = 0;
        DefaultTableModel introModel = (DefaultTableModel) introTable.getModel();
        String queryResult = null;
        String query = "Score: ";
        
        introRowCount = introTable.getRowCount();
        for (int i = 0; i < introRowCount; ++i)
        {
            ((DefaultTableModel) introTable.getModel()).removeRow(0);           
        }
        
        
        File[] files = new File("./Sheets").listFiles();
        String[] splittedString = null;
        
        
        if (files != null)
        {
            // goes through all files and searches for scout sheets
            for (File file:files) 
            {  
                Scanner scanner = new Scanner(file);
                
                String wholeString = file.getName();
                if (!file.isDirectory() && wholeString.startsWith("ScoutSheet")) 
                {
                        System.out.println("Scouting Sheet: " + file.getName());         
                        splittedString = splitString(wholeString);
                        queryResult = queryFind(scanner, query);
                }
                        
                        // the row-adding thing will be edited to accomodate
                        // the actual fields when one row per team
                        introModel.addRow(new Object[]{splittedString[1],
                        splittedString[2], splittedString[3], queryResult});
                
                    
            }
               
        }
       
        
        else
        {
            System.out.println("No files in directory");
        }        
        
        // used for data table
        return splittedString;
    }
    
    private String[] splitString(String split)  
    {  // takes scouting filename and returns its info
        String[] splittedString = null;
        int tempInt = 0;
        splittedString = split.split("-");
                        
        // iterates through each piece of file name (separated by -)
        for (String string : splittedString)
            {
                // System.out.println(string);
                if (string.endsWith(".sav"))
                {
                    splittedString[tempInt] = string.split(".sav")[0];
                    // System.out.println("Changed to " + splittedString[tempInt]);
                } 
                tempInt++;
            }
      
        return splittedString;
    }
    
    
    private String queryFind(Scanner scanner, String query)
    {
        while (scanner.hasNextLine()) {
                            
        // todo: use query as a loop for each sheet stat
        String fileLine = scanner.nextLine();
        if(fileLine.contains(query)) 
            return fileLine.split(query)[1];
        }
        return "String not found.";
    }
    
    private void windowSet() {
 
         // sets window to center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        double width = dim.getWidth();
        double height = dim.getHeight();
    
        // alerts user if screen resolution is below 1024x768 
        if (width<1024 || height<768)
        
        {
            JOptionPane.showMessageDialog(null,
            "Your screen resolution is not supported. Some "
                    + "elements may not appear or may appear incorrectly.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        }
    
        // sets window to center of screen
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }
    
    public static void main(String args[]) {
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton introRefresh;
    private javax.swing.JTable introTable;
    private javax.swing.JButton introView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mainMatchForm;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable mainTable;
    // End of variables declaration//GEN-END:variables
}
