/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scouting2016;

import java.awt.Desktop;
import java.awt.Dimension;
import static java.awt.SystemColor.desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author adam
 */
public class TeamFrame extends javax.swing.JFrame {

    private int introTeamFinal;
    private ArrayList<String> teamColumnDefault = new ArrayList<>();
    
    /**
     * Creates new form teamFrame
     */
    public TeamFrame(int introTeam) throws FileNotFoundException, IOException {
        
        introTeamFinal = introTeam;
        
        initComponents();
        
        DefaultTableModel teamModel = (DefaultTableModel) teamTable.getModel();
        for (int i = 0; i < teamModel.getColumnCount(); i++) {
                teamColumnDefault.add(teamModel.getColumnName(i));
            }
        
        
        try   
        {
            // sets look and feely
            UIManager.setLookAndFeel
            ("javax.swing.plaf.metal.MetalLookAndFeel");

        }  
        catch (Exception e)
        {}
        
        
        tableSet(introTeamFinal);
        
        
        // sets window to center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        double width = dim.getWidth();
        double height = dim.getHeight();
    
        // sets window to center of screen
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        setVisible(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();
        queryCombo = new javax.swing.JComboBox<>();
        queryAddColumn = new javax.swing.JButton();
        matchOpenButton = new javax.swing.JButton();
        resetColumns = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sheets for Team " + introTeamFinal);

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Scouter Name", "Team #", "Match #", "Grand Total Points", "Overall Performance", "Driving System", "Driving System Functionality", "Mover System", "Mover System Functionality", "Foul Points", "Additional Comments", "Autonomous Points", "Teleoperation Points", "Coopertition Points"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);

        teamTable.setAutoCreateRowSorter(true);
        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Match #", "Scouter name", "Score", "Won"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teamTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(teamTable);

        queryCombo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        queryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        queryAddColumn.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        queryAddColumn.setText("Add Column");
        queryAddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryAddColumnActionPerformed(evt);
            }
        });

        matchOpenButton.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        matchOpenButton.setText("Open Match Sheet");
        matchOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchOpenButtonActionPerformed(evt);
            }
        });

        resetColumns.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        resetColumns.setText("Reset Columns");
        resetColumns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetColumnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(627, 627, 627)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(matchOpenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetColumns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(queryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(queryAddColumn)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryAddColumn)
                    .addComponent(matchOpenButton)
                    .addComponent(resetColumns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(586, 586, 586))
        );

        setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamTableMouseClicked
        
    }//GEN-LAST:event_teamTableMouseClicked

    private void queryAddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryAddColumnActionPerformed
        Parser parse = new Parser();
        ArrayList <String> columnNames = new ArrayList<>();
        DefaultTableModel teamModel = (DefaultTableModel) teamTable.getModel();
        try 
        {
            for (int i = 0; i < teamModel.getColumnCount(); i++) {
                columnNames.add(teamModel.getColumnName(i));
            }
            columnNames.add(queryCombo.getSelectedItem().toString());
            System.out.println(columnNames);
            
            String columnNamesArray[] = new String[columnNames.size()];              
		for(int i = 0; i < columnNames.size(); i++){
		  columnNamesArray[i] = columnNames.get(i);
		}
            
            teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, columnNamesArray));
            
        }
        catch (Exception e) 
        {
            System.out.println("Error");
        }
        
        try {
            parse.expandTable(introTeamFinal, teamTable);
        } catch (IOException ex) {
            System.out.println("Error (IOE)");
        }
        
    }//GEN-LAST:event_queryAddColumnActionPerformed

    private void matchOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchOpenButtonActionPerformed
        DefaultTableModel teamModel = (DefaultTableModel) teamTable.getModel();
        int selRow = teamTable.getSelectedRow();
        int fileIndex = 0;

        File[] files = new File("./Sheets").listFiles();

        if (files != null)
        {
            // goes through all files and searches for scout sheets for specific team
            for (File file:files)
            {
                String wholeString = file.getName();
                if (!file.isDirectory() && wholeString.startsWith("ScoutSheet-" +
                    String.valueOf(introTeamFinal)))
            {
                if (fileIndex == selRow)
                {
                    try
                    {
                        Desktop.getDesktop().open(file);
                        break;
                    }
                    catch (IOException ex)
                    {
                        System.out.println("File not found");
                    }
                }
                else
                {
                    fileIndex++;
                }
            }
        }
        }
    }//GEN-LAST:event_matchOpenButtonActionPerformed

    private void resetColumnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetColumnsActionPerformed
        Parser parse = new Parser();
        String columnNamesArray[] = new String[teamColumnDefault.size()];              
		for(int i = 0; i < teamColumnDefault.size(); i++){
		  columnNamesArray[i] = teamColumnDefault.get(i);
		}
            
            teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {}, columnNamesArray));
            
        try {
            parse.expandTable(introTeamFinal, teamTable);
        } catch (IOException ex) {
            System.out.println("Error (IOE)");
        }    
         
    }//GEN-LAST:event_resetColumnsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public void tableSet(int introTeam) throws FileNotFoundException, IOException {
    
        Parser parse = new Parser();
        parse.expandTable(introTeam, teamTable);
        parse.comboSet(queryCombo, queryAddColumn);
    }
    
    
    
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton matchOpenButton;
    private javax.swing.JButton queryAddColumn;
    private javax.swing.JComboBox<String> queryCombo;
    private javax.swing.JButton resetColumns;
    private javax.swing.JTable teamTable;
    // End of variables declaration//GEN-END:variables
}
